//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTEHY.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Content { get; set; }
    }
}
