//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTEHY.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public string FunctionId { get; set; }
        public string GroupId { get; set; }
        public string CommandId { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Function Function { get; set; }
        public virtual GroupUser GroupUser { get; set; }
    }
}
