//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTEHY.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string TecherId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public string WorkPlace { get; set; }
        public string WebSite { get; set; }
        public string Content { get; set; }
        public string Img { get; set; }
    }
}
