// <auto-generated />
namespace UTEHY.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version_102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_102));
        
        string IMigrationMetadata.Id
        {
            get { return "202101011547243_version_1.0.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
